# Generated by Django 6.1.1 on 2026-10-07 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in Kenyan shillings (KES).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
